### ISSUE TITLE
Invoices missing in production

### ISSUE THREAD

**Issue by ravirkkm** [philfree/ofuz#22]
In the production (ofuz.afternow.io) ,  2 invoices are missing.
Table `invoice`

**Comment by ravirkkm** [comment]
I followed these 3 steps:
1. Immediately pointed the DB to `ofuzdev` to find out the difference and Philippe was able to get his invoices back. 
2. Created a branch `connects-to-ofuzdev-db` which connects to `ofuzdev` db and pointed to this branch in production server so that Philippe can check the invoices.
3. Looked into the tables from both the databases (ofuzdev and ofuz) to find out the difference in `invoice` table and found that `ofuz` db was missing 2 records in invoice table.  Wrote an import statement to get those two records from `ofuzdev.invoice` table:

```
mysqldump -t -u username -pPWD ofuzdev invoice --where="idinvoice in (24,25)";
```
and executed the queries in `ofuz.invoice` table.
4. Deleted the branch `connects-to-ofuzdev-db` and pointed to `develop` branch (which has `ofuz` db connection) in production server.

T{8:00}

**Comment by philfree** [comment]
I see the 2 missing invoices now, closing the task
